runtime: python
env: flex
entrypoint: gunicorn -b : $PORT main:application
runtime_config:
  python_version: 3

manual_scaling:
  instances: 1
resources:
  cpu: 2
  memory_gb: 8
  disk_size_gb: 20   
readiness_check:
  app_start_timeout_sec: 30000
